application: twcodereview 
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: /gaetest/gaeunit.py
- url: /static
  static_dir: static
- url: /.*
  script: /src/guru.py

inbound_services:
- xmpp_message
